module.exports = [
	{
		firstName: 'John',
		lastName: 'Doe',
		admin: false,
		phoneNumber: '09173450089',
		email: 'abc@gmail.com',
		gender: 'male',
		birthDate: new Date().toISOString(),
		img: 'images/man2.jpg',
		password: '123',
		disabled: false,
	},
	{
		firstName: 'jasmine',
		lastName: 'Smith',
		admin: false,
		phoneNumber: '09173864321',
		email: 'abc@gmail.com',
		gender: 'female',
		birthDate: new Date().toISOString(),
		img: 'images/woman2.jpg',
		password: '123',
		disabled: false,
	},
	{
		firstName: 'Jane',
		lastName: 'Doe',
		admin: false,
		phoneNumber: '09378864321',
		email: 'abc@gmail.com',
		gender: 'female',
		birthDate: new Date().toISOString(),
		img: 'images/woman1.jpg',
		password: '123',
		disabled: false,
	},
	{
		firstName: 'Mike',
		lastName: 'Ross',
		admin: true,
		phoneNumber: '09389964322',
		email: 'abc@gmail.com',
		gender: 'male',
		birthDate: new Date().toISOString(),
		img: 'images/man1.jpg',
		password: '123',
		disabled: false,
	},
	{
		firstName: 'Sina',
		lastName: 'Abedi',
		admin: true,
		phoneNumber: '09038394538',
		email: 'abc@gmail.com',
		gender: 'male',
		birthDate: new Date().toISOString(),
		img: 'images/users.png',
		password: '123',
		disabled: false,
	},
	{
		firstName: 'John',
		lastName: 'Wick',
		admin: true,
		phoneNumber: '09038394545',
		email: 'abc@gmail.com',
		gender: 'male',
		birthDate: new Date().toISOString(),
		img: 'images/JohnWick.jpg',
		password: '123',
		disabled: false,
	},
];
